### ISSUE TITLE
Cannot open HMI file

### ISSUE THREAD

**Issue by veraabad** [EA5KL/NextionScreen#1]
I tried to open the HMI file in order to compile a TFT for my Nextion display, but the Nextion Editor couldn't open it and instead would show and error. The error was "Could not load resource or resource has been corrupted"

I'm using the latest Nextion Editor 0.58

**Comment by EA5KL** [comment]
Good morning!
I don't know what the problem could be, but I'll upload the file again this
morning. The first thing I thought was the version of the nextion editor,
but you're in the latest.
I'll send you an email when uploaded. If you have problems don't hesitate
to contact me.

73, Mariano.

**Comment by EA5KL** [comment]
Done! I just reuploaded the new version. Tell me if all is ok.

**Comment by veraabad** [comment]
@EA5KL Thanks, I was able to open it now. I wasn't able to compile for my screen though because I have the 2.4" Nextion Basic. Would you consider adapting your layout for the smaller screen?

**Comment by EA5KL** [comment]
At the moment I couldn't do it, the 3.5 isn't finished yet, and all the
information showed isn't practical for a 2.4. But who knows, if I have free
time, I could try it.
73

**Comment by veraabad** [comment]
I understand. Thanks anyways
